### ISSUE TITLE
解决方案按模块功能拆分成多个工程

### ISSUE THREAD

**Issue by JackSho** [xf-bnb/SourceCounter#8]
## 问题描述

* 当前项目只有一个解决方案（Windows：SourceCounter.sln， Mac：SourceCounter.xcworkspace），实际上解决方案（或者叫工作区）应该是更大范围的定义，我们将该项目看作解决方案，那么其中的 config、counter、third 应该是解决方案下的工程，应该拆分成单独的工程。这些工程彼此组合在一起，形成完整的解决方案。
* 这些拆分出来的工程之间的依赖，不管是以动态库，还是静态库形式，都将比现在直接将代码编译进来的方式更好。

**Comment by JackSho** [comment]
甚至这些拆分出来的工程都可以单独发布，拥有自己的版本，解决方案中使用某些依赖管理方式，依赖这些工程的特定版本，管理起来更加清晰。

**Comment by xiong-frank** [comment]
目前有个 `split-module` 分支已经是按这种思路做的了，我是按照统计分析库，控制台界面，gui界面，测试项目来划分的，目前仅配置好了 vs 工程文件，并且已经合并到了 `dev` 分支，是一个可运行的版本，包含部分测试。但是我会继续在 `split-module` 分支上更新，然后合并到 dev。
