### ISSUE TITLE
语法配置数据结构不能体现多种同类语言的语法解析规则

### ISSUE THREAD

**Issue by xiong-frank** [xf-bnb/SourceCounter#9]
### 问题描述
当前的配置文件要求的语言配置结构如下：
```json
{
"C": {
        "extensions": [".cpp", ".cc", ".inl"],
        "options": [ ["//"],
                     [["/*", "*/"]],
                     [["\"", "\""]],
                     [] 
                   ]
    }
}
```
* 其中 `options` 字段配置的是语言的语法特征，分别为：单行注释符，多行注释符，普通字符串符号，原生字符串符号。假定有另外一种语言 “X“，其语法特征与C语言一样，但配置不一样，那么需要配置”X“语言的语法特征，但即使配置了，由于”X“语言并非内置支持的语言，因此依然不能正确分析。
* 另外，即使是C语言，如果统计工具的使用者想自定义规则，或者按别的语言的语法规则进行统计，也不能得到支持。

### 解决标识
对于任意配置的语言可以配置其对应的同类的语言分析器，并按照指定的语言规则进行统计，同时也可以自定义语法配置项。以上述C语言的配置为例，以下几种情形能符合预期：
* 有语言”X“，配置如下：
```json
{
"X": {
        "analyzer":"C",
        "extensions": [".x", ".xx", ".xxx"]
    }
}
```
能直接按照C语言的配置和分析规则，对`.x .xx .xxx`文件进行统计。
* 有语言”X“，配置如下：
```json
{
"X": {
        "analyzer":"C",
        "extensions": [".x", ".xx", ".xxx"],
        "syntax": [ ["##"],
                     [["[*", "*]"]],
                     [["\"", "\""]],
                     [] 
                   ]
    }
}
```
能按照自己的配置和C语言的分析规则，对`.x .xx .xxx`文件进行统计。
* 即使C语言有内置规则，但依然配置如下：
```json
{
"C": {
        "analyzer":"C++",
        "extensions": [".c", ".x"],
        "syntax": [ ["##"],
                     [["[*", "*]"]],
                     [["\"", "\""]],
                     [] 
                   ]
    }
}
```
那么C语言将按照此配置和C++语言的分析规则对 `.c .x` 文件进行统计。
* 有语言”X“，配置如下：
```json
{
"X": {
        "analyzer":"Y",
        "extensions": [".x", ".xx", ".xxx"]
    }
}
```
由于Y语言非支持的分析器，因此指定分析器”Y“将提示配置错误。

### 问题分析
没有区分出要分析的目标语言和分析器的概念，以及分析器和语言之间的对应关系。正确的设计应为，实现无状态的分析器，一种类型的分析器应该可以根据不同的配置对多种语言进行分析统计。

**Comment by JackSho** [comment]
分析器 `analyzer` 应该是有状态的，对不同语言的统计支持，实际上是分析器与分析规则的组合。

**Comment by xiong-frank** [comment]
我不确定是否正确的表达了我的意思，因此在这里再解释一遍，以减少不必要的歧义。

首先说明一下 `无状态` 一词，通俗一点的说法就是 **输出只与输入有关**，与其他的任何因素无关，我想你应该也同意这一点。

那么在这里，我描述的 **实现无状态的分析器**，意味着分析器的输出分析结果只与输入的文件以及语法规则有关，分析器仅实现为对某类相同语法特征的语言的分析算法。但分析器可能也有多种，因为某些语言的语法特征差异较大，并不能使用相同的分析算法。但也有一些语言的特征相似，可以使用相同的算法进行分析，只是配置的规则不一样而已。

上述是我对 **无状态的分析器** 的解释。目前的设计符合这一思想，但不符合分析器和语言一对多的关系，主要体现在规则配置上面，即通过配置不能表达分析器和语言的区别。因为现在的配置格式仅支持了配置语言名称，但该语言应该使用何种分析算法进行分析我并不能确定，仅在分析器类型实现部分映射了部分语言。事实上我也不可能了解所有的语言应该使用的分析算法，同时我也并没有实现所有类型的分析器，况且世界上不断的还有新的语言被发明出来。

因此我打算实现多种分析器算法，以支持更多的语言分析统计。可能某种分析器可以根据配置不同支持多种语言的分析，例如：可以将C和Java使用同一种分析器进行分析，Clojure 和 ClojureScript 也一样。也可能某种分析器仅支持一种语言(例如C++？我不确定)。但我将保证实现的多种分析器肯定是具有不同算法行为的，因此，当用户在配置的时候，只需要了解所配置的语言是否在已有的分析器中有匹配的，如果没有，那我们可能需要编码实现了，这也是后期维护的时候需要做的事情，但目前优先级不高。最主要的是，我将 **这一行为交由用户来决定** 了。
